import { createElement, useEffect, useMemo, useState } from 'react'
import { getStroke } from 'perfect-freehand'
import { Link } from 'react-router'
import Section from '../components/Section.js'
import SectionHeader from '../components/SectionHeader.js'
import HomeSectionRail from '../components/HomeSectionRail.js'
import {
  siteContentBundle,
  selectHomePageData,
} from '../content/index.js'

const homeData = selectHomePageData(siteContentBundle)


/*
 * STEP 05Z — image-feature freehand brush
 *
 * Source logo reference:
 * 189 × 126 px.
 *
 * The centerlines below are derived from the two dominant ribbon/check
 * trajectories in the logo silhouette. They intentionally do NOT close
 * into circles: each stroke descends into a valley, then accelerates
 * upward. The final polygon is generated by perfect-freehand.
 */

const WF_BRUSH_VIEWBOX = Object.freeze({
  width: 420,
  height: 140,
})

const WF_LOGO_FEATURES = Object.freeze({
  checkA: Object.freeze([
    [36, 86],
    [64, 93],
    [84, 108],
    [116, 111],
    [144, 110],
    [176, 104],
    [182, 91],
    [187, 78],
    [193, 66],
    [220, 56],
    [244, 50],
  ]),
  checkB: Object.freeze([
    [205, 87],
    [220, 100],
    [236, 111],
    [262, 106],
    [282, 89],
    [311, 59],
    [340, 29],
    [393, 11],
  ]),
})

function clamp01(value) {
  return Math.max(0, Math.min(1, value))
}

function easeOutCubic(value) {
  const t = clamp01(value)
  return 1 - ((1 - t) ** 3)
}

function catmullRomPoint(p0, p1, p2, p3, t) {
  const t2 = t * t
  const t3 = t2 * t

  return [
    0.5
      * (
        (2 * p1[0])
        + (-p0[0] + p2[0]) * t
        + (2 * p0[0] - 5 * p1[0] + 4 * p2[0] - p3[0]) * t2
        + (-p0[0] + 3 * p1[0] - 3 * p2[0] + p3[0]) * t3
      ),
    0.5
      * (
        (2 * p1[1])
        + (-p0[1] + p2[1]) * t
        + (2 * p0[1] - 5 * p1[1] + 4 * p2[1] - p3[1]) * t2
        + (-p0[1] + 3 * p1[1] - 3 * p2[1] + p3[1]) * t3
      ),
  ]
}

function sampleCatmullRom(anchorPoints, samplesPerSegment = 10) {
  if (anchorPoints.length < 2) {
    return anchorPoints
  }

  const sampled = []

  for (let index = 0; index < anchorPoints.length - 1; index += 1) {
    const p0 = anchorPoints[Math.max(0, index - 1)]
    const p1 = anchorPoints[index]
    const p2 = anchorPoints[index + 1]
    const p3 = anchorPoints[Math.min(anchorPoints.length - 1, index + 2)]

    for (let sampleIndex = 0; sampleIndex < samplesPerSegment; sampleIndex += 1) {
      const t = sampleIndex / samplesPerSegment
      sampled.push(catmullRomPoint(p0, p1, p2, p3, t))
    }
  }

  sampled.push(anchorPoints[anchorPoints.length - 1])

  return sampled
}

function pressureForCheckA(t) {
  if (t < 0.12) {
    return 0.30 + (0.72 - 0.30) * (t / 0.12)
  }

  if (t < 0.48) {
    return 0.72 + (0.94 - 0.72) * ((t - 0.12) / 0.36)
  }

  if (t < 0.70) {
    return 0.94 + (0.72 - 0.94) * ((t - 0.48) / 0.22)
  }

  return 0.72 + (0.16 - 0.72) * ((t - 0.70) / 0.30)
}

function pressureForCheckB(t) {
  if (t < 0.12) {
    return 0.26 + (0.80 - 0.26) * (t / 0.12)
  }

  if (t < 0.44) {
    return 0.80 + (1.00 - 0.80) * ((t - 0.12) / 0.32)
  }

  if (t < 0.68) {
    return 1.00 + (0.70 - 1.00) * ((t - 0.44) / 0.24)
  }

  return 0.70 + (0.08 - 0.70) * ((t - 0.68) / 0.32)
}

function withPressure(centerline, pressureProfile) {
  const lastIndex = Math.max(1, centerline.length - 1)

  return centerline.map(([x, y], index) => [
    x,
    y,
    pressureProfile(index / lastIndex),
  ])
}

function getSvgPathFromStroke(stroke) {
  const length = stroke.length

  if (length < 4) {
    return ''
  }

  const average = (left, right) => (left + right) / 2

  let pointA = stroke[0]
  let pointB = stroke[1]
  const pointC = stroke[2]

  let result =
    `M${pointA[0].toFixed(2)},${pointA[1].toFixed(2)} `
    + `Q${pointB[0].toFixed(2)},${pointB[1].toFixed(2)} `
    + `${average(pointB[0], pointC[0]).toFixed(2)},`
    + `${average(pointB[1], pointC[1]).toFixed(2)} T`

  for (let index = 2; index < length - 1; index += 1) {
    pointA = stroke[index]
    pointB = stroke[index + 1]

    result +=
      `${average(pointA[0], pointB[0]).toFixed(2)},`
      + `${average(pointA[1], pointB[1]).toFixed(2)} `
  }

  result += 'Z'
  return result
}

function buildFreehandPath(points, visibleProgress, size) {
  const progress = clamp01(visibleProgress)

  if (progress <= 0 || points.length < 2) {
    return ''
  }

  const count = Math.max(
    2,
    Math.min(
      points.length,
      Math.ceil(points.length * progress),
    ),
  )

  const partialPoints = points.slice(0, count)

  const stroke = getStroke(partialPoints, {
    size,
    thinning: 0.68,
    smoothing: 0.78,
    streamline: 0.34,
    simulatePressure: false,
    start: {
      taper: 10,
      cap: true,
    },
    end: {
      taper: progress >= 0.999 ? 34 : 3,
      cap: false,
    },
  })

  return getSvgPathFromStroke(stroke)
}

function useReducedMotion() {
  const [reducedMotion, setReducedMotion] = useState(false)

  useEffect(() => {
    const mediaQuery = window.matchMedia(
      '(prefers-reduced-motion: reduce)',
    )

    const sync = () => setReducedMotion(mediaQuery.matches)
    sync()

    mediaQuery.addEventListener?.('change', sync)

    return () => {
      mediaQuery.removeEventListener?.('change', sync)
    }
  }, [])

  return reducedMotion
}

function WinningFundSloganBrush() {
  const reducedMotion = useReducedMotion()

  const checkAPoints = useMemo(
    () => withPressure(
      sampleCatmullRom(WF_LOGO_FEATURES.checkA, 10),
      pressureForCheckA,
    ),
    [],
  )

  const checkBPoints = useMemo(
    () => withPressure(
      sampleCatmullRom(WF_LOGO_FEATURES.checkB, 11),
      pressureForCheckB,
    ),
    [],
  )

  const finalPaths = useMemo(
    () => ({
      checkA: buildFreehandPath(checkAPoints, 1, 42),
      checkB: buildFreehandPath(checkBPoints, 1, 46),
    }),
    [checkAPoints, checkBPoints],
  )

  const [paths, setPaths] = useState(() => ({
    checkA: '',
    checkB: '',
  }))

  useEffect(() => {
    if (reducedMotion) {
      setPaths({
        checkA: buildFreehandPath(checkAPoints, 1, 42),
        checkB: buildFreehandPath(checkBPoints, 1, 46),
      })
      return undefined
    }

    let frameId = 0
    const startedAt = performance.now()

    const checkAStart = 1340
    const checkADuration = 760
    const checkBStart = 1700
    const checkBDuration = 920

    const draw = (now) => {
      const elapsed = now - startedAt

      const checkAProgress = easeOutCubic(
        (elapsed - checkAStart) / checkADuration,
      )

      const checkBProgress = easeOutCubic(
        (elapsed - checkBStart) / checkBDuration,
      )

      setPaths({
        checkA: buildFreehandPath(
          checkAPoints,
          checkAProgress,
          42,
        ),
        checkB: buildFreehandPath(
          checkBPoints,
          checkBProgress,
          46,
        ),
      })

      if (checkAProgress < 1 || checkBProgress < 1) {
        frameId = requestAnimationFrame(draw)
      }
    }

    frameId = requestAnimationFrame(draw)

    return () => {
      cancelAnimationFrame(frameId)
    }
  }, [
    checkAPoints,
    checkBPoints,
    reducedMotion,
  ])

  return createElement(
    'svg',
    {
      className: 'wf-home-kinetic-slogan__brush',
      viewBox:
        `0 0 ${WF_BRUSH_VIEWBOX.width} ${WF_BRUSH_VIEWBOX.height}`,
      preserveAspectRatio: 'none',
      'aria-hidden': 'true',
      focusable: 'false',
    },
    createElement(
      'defs',
      null,
      createElement(
        'linearGradient',
        {
          id: 'wf-slogan-brush-gradient-a',
          gradientUnits: 'userSpaceOnUse',
          x1: '34',
          y1: '108',
          x2: '250',
          y2: '42',
        },
        createElement('stop', {
          offset: '0%',
          stopColor: '#89E2FA',
        }),
        createElement('stop', {
          offset: '48%',
          stopColor: '#69CCF5',
        }),
        createElement('stop', {
          offset: '78%',
          stopColor: '#269DEB',
        }),
        createElement('stop', {
          offset: '100%',
          stopColor: '#0079FA',
        }),
      ),
      createElement(
        'linearGradient',
        {
          id: 'wf-slogan-brush-gradient-b',
          gradientUnits: 'userSpaceOnUse',
          x1: '205',
          y1: '112',
          x2: '398',
          y2: '8',
        },
        createElement('stop', {
          offset: '0%',
          stopColor: '#69CCF5',
        }),
        createElement('stop', {
          offset: '42%',
          stopColor: '#269DEB',
        }),
        createElement('stop', {
          offset: '72%',
          stopColor: '#0079FA',
        }),
        createElement('stop', {
          offset: '100%',
          stopColor: '#1034DC',
        }),
      ),
    ),
    createElement('path', {
      className:
        'wf-home-kinetic-slogan__underpaint wf-home-kinetic-slogan__underpaint--1',
      d: finalPaths.checkA,
      fill: 'url(#wf-slogan-brush-gradient-a)',
    }),
    createElement('path', {
      className:
        'wf-home-kinetic-slogan__underpaint wf-home-kinetic-slogan__underpaint--2',
      d: finalPaths.checkB,
      fill: 'url(#wf-slogan-brush-gradient-b)',
    }),
    createElement('path', {
      className:
        'wf-home-kinetic-slogan__check wf-home-kinetic-slogan__check--1',
      d: paths.checkA,
      fill: 'url(#wf-slogan-brush-gradient-a)',
    }),
    createElement('path', {
      className:
        'wf-home-kinetic-slogan__check wf-home-kinetic-slogan__check--2',
      d: paths.checkB,
      fill: 'url(#wf-slogan-brush-gradient-b)',
    }),
  )
}

function HeroWordRow({
  number,
  english,
  delayClass,
  annotation,
}) {
  return createElement(
    'div',
    {
      className: `wf-home-kinetic-row ${delayClass}`,
    },
    createElement(
      'div',
      { className: 'wf-home-kinetic-row__meta' },
      createElement('span', null, number),
      annotation
        ? createElement(
            'span',
            { className: 'wf-home-kinetic-row__annotation' },
            annotation,
          )
        : null,
    ),
    createElement(
      'span',
      { className: 'wf-home-kinetic-row__text-slot' },
      createElement(
        'span',
        {
          className: 'wf-home-kinetic-row__ghost',
          'aria-hidden': 'true',
        },
        english,
      ),
      createElement(
        'span',
        {
          className: 'wf-home-kinetic-row__reveal',
          'aria-hidden': 'true',
        },
        createElement(
          'span',
          { className: 'wf-home-kinetic-row__reveal-word' },
          english,
        ),
      ),
    ),
  )
}

function HomeHero() {
  return createElement(
    'section',
    {
      id: 'home-hero',
      className: 'wf-home-hero wf-home-hero--kinetic-entrance',
      'aria-labelledby': 'wf-home-title',
    },
    createElement(
      'div',
      {
        className:
          'wf-home-hero__inner wf-home-hero__inner--kinetic-entrance',
      },
      createElement(
        'div',
        { className: 'wf-home-hero__kinetic-side' },
        createElement(
          'div',
          { className: 'wf-home-hero__impact-meta' },
          createElement('span', null, '01 / HOME'),
          createElement(
            'strong',
            { className: 'wf-home-hero__impact-kicker' },
            '투자·경제 학회',
          ),
        ),
      ),
      createElement(
        'div',
        { className: 'wf-home-hero__kinetic-main' },
        createElement(
          'div',
          { className: 'wf-home-hero__impact-brand' },
          'WINNINGFUND',
        ),
        createElement(
          'h1',
          {
            id: 'wf-home-title',
            className: 'wf-home-hero__kinetic-title-a11y',
          },
          homeData.hero.englishIdentity,
        ),
        createElement(
          'div',
          {
            className: 'wf-home-kinetic-list',
            'aria-hidden': 'true',
          },
          createElement(HeroWordRow, {
            number: '01',
            english: 'INVESTMENT',
            delayClass: 'wf-home-kinetic-row--1',
          }),
          createElement(HeroWordRow, {
            number: '02',
            english: 'ECONOMICS',
            delayClass: 'wf-home-kinetic-row--2',
            annotation: 'AND',
          }),
          createElement(HeroWordRow, {
            number: '03',
            english: 'CLUB',
            delayClass: 'wf-home-kinetic-row--3',
          }),
        ),
        createElement(
          'div',
          { className: 'wf-home-kinetic-footer' },
          createElement(
            'div',
            {
              className: 'wf-home-kinetic-term',
              'aria-label': '현재 기수 18-2',
            },
            createElement('span', null, 'CURRENT TERM'),
            createElement('strong', null, '18—2'),
          ),
          createElement('span', {
            className: 'wf-home-kinetic-footer__divider',
            'aria-hidden': 'true',
          }),
          createElement(
            'p',
            {
              className: 'wf-home-kinetic-slogan',
              'aria-label': homeData.hero.koreanSlogan,
            },
            createElement(WinningFundSloganBrush),
            createElement(
              'span',
              { className: 'wf-home-kinetic-slogan__text' },
              homeData.hero.koreanSlogan,
            ),
          ),
        ),
      ),
    ),
  )
}

function ShortIntroduction() {
  const introduction = homeData.shortIntroduction

  return createElement(
    Section,
    {
      sectionId: 'short-introduction',
      spacingVariant: 'compact',
      className: 'wf-home-intro',
    },
    createElement(
      'div',
      { className: 'wf-home-intro__grid' },
      createElement(
        'div',
        { className: 'wf-home-section-index' },
        '02 / 소개',
      ),
      createElement(
        'div',
        { className: 'wf-home-intro__statement' },
        createElement(
          'p',
          { className: 'wf-home-intro__name' },
          introduction?.heading ?? '위닝펀드',
        ),
        createElement(
          'p',
          { className: 'wf-home-intro__identity' },
          introduction?.supportingIdentity ?? '투자·경제 학회',
        ),
        introduction?.bodyCopy
          ? createElement(
              'p',
              { className: 'wf-home-intro__copy' },
              introduction.bodyCopy,
            )
          : null,
      ),
    ),
  )
}

function ProgramOverview() {
  return createElement(
    Section,
    {
      sectionId: 'program-overview',
      className: 'wf-home-programs',
    },
    createElement(
      'div',
      { className: 'wf-home-section-index' },
      '03 / 활동',
    ),
    createElement(SectionHeader, {
      title: '주요 활동',
      headingLevel: 2,
    }),
    createElement(
      'div',
      { className: 'wf-home-programs__list' },
      ...homeData.programOverview.map(
        (program, index) =>
          createElement(
            Link,
            {
              key: program.activityId,
              to: program.target,
              className: 'wf-home-program',
            },
            createElement(
              'span',
              { className: 'wf-home-program__number' },
              String(index + 1).padStart(2, '0'),
            ),
            createElement(
              'span',
              { className: 'wf-home-program__body' },
              createElement(
                'strong',
                { className: 'wf-home-program__title' },
                program.homeLabel,
              ),
              program.homeSummary
                ? createElement(
                    'span',
                    { className: 'wf-home-program__summary' },
                    program.homeSummary,
                  )
                : null,
            ),
            createElement(
              'span',
              {
                className: 'wf-home-program__arrow',
                'aria-hidden': 'true',
              },
              '↗',
            ),
          ),
      ),
    ),
  )
}

function MissionSection() {
  const mission = homeData.mission
  if (!mission?.items?.length) return null

  return createElement(
    Section,
    {
      sectionId: 'mission',
      className: 'wf-home-mission',
    },
    createElement(
      'div',
      { className: 'wf-home-section-index' },
      '04 / 방향',
    ),
    createElement(SectionHeader, {
      title: mission.title,
      headingLevel: 2,
    }),
    createElement(
      'div',
      { className: 'wf-home-mission__grid' },
      ...mission.items.map((item) =>
        createElement(
          'article',
          {
            key: item.id,
            className: 'wf-home-mission__item',
          },
          createElement(
            'span',
            { className: 'wf-home-mission__number' },
            String(item.order).padStart(2, '0'),
          ),
          createElement(
            'h3',
            { className: 'wf-home-mission__heading' },
            item.heading,
          ),
          item.description
            ? createElement(
                'p',
                { className: 'wf-home-mission__copy' },
                item.description,
              )
            : null,
        ),
      ),
    ),
  )
}

function SemesterContents() {
  const semester = homeData.semesterContents

  if (
    !semester ||
    semester.semesterId !==
      siteContentBundle.siteConfig.homeSemesterId
  ) {
    return null
  }

  return createElement(
    Section,
    {
      sectionId: 'contents-18-2',
      className: 'wf-home-semester',
    },
    createElement(
      'div',
      { className: 'wf-home-section-index' },
      '05 / 18-2',
    ),
    createElement(
      'div',
      { className: 'wf-home-semester__heading-row' },
      createElement(SectionHeader, {
        title: semester.title,
        headingLevel: 2,
      }),
      createElement(
        'div',
        {
          className: 'wf-home-semester__term',
          'aria-hidden': 'true',
        },
        '18—2',
      ),
    ),
    semester.scheduleItems?.length
      ? createElement(
          'ol',
          { className: 'wf-home-semester__timeline' },
          ...semester.scheduleItems.map((item) =>
            createElement(
              'li',
              {
                key: item.id,
                className: 'wf-home-semester__item',
              },
              createElement(
                'span',
                { className: 'wf-home-semester__date' },
                item.period ?? item.dateLabel,
              ),
              createElement(
                'strong',
                { className: 'wf-home-semester__item-title' },
                item.title,
              ),
              item.description
                ? createElement(
                    'span',
                    { className: 'wf-home-semester__description' },
                    item.description,
                  )
                : null,
            ),
          ),
        )
      : createElement('div', {
          className: 'wf-home-semester__source-line',
          'data-content-state': semester.sourceStatus,
          'aria-hidden': 'true',
        }),
  )
}

export default function HomePage() {
  return createElement(
    'div',
    { className: 'wf-home' },
    createElement(HomeSectionRail),
    createElement(HomeHero),
    createElement(ShortIntroduction),
    createElement(ProgramOverview),
    createElement(MissionSection),
    createElement(SemesterContents),
  )
}
