export const CONTENT_SOURCE_STATUS = Object.freeze({
  AUTHORITATIVE:'AUTHORITATIVE', PARTIAL:'PARTIAL', UNAVAILABLE:'UNAVAILABLE',
  UNKNOWN:'UNKNOWN', PLACEHOLDER_DEMO:'PLACEHOLDER_DEMO',
})
export const MEMBER_DATA_STATUS = Object.freeze({
  AVAILABLE:'AVAILABLE', PARTIAL:'PARTIAL',
  UNAVAILABLE:'UNAVAILABLE', KNOWN_EMPTY:'KNOWN_EMPTY',
})
export const COHORT_STATUS = Object.freeze({CURRENT:'CURRENT',HISTORICAL:'HISTORICAL'})
export const RECRUITMENT_STATUS = Object.freeze({
  COMING_SOON:'COMING_SOON', OPEN:'OPEN', CLOSED:'CLOSED', ARCHIVED:'ARCHIVED',
})
export const RECRUITMENT_VIEW = Object.freeze({
  CONTENT_UNAVAILABLE:'CONTENT_UNAVAILABLE',
  COMING_SOON:'COMING_SOON', OPEN:'OPEN', CLOSED:'CLOSED', ARCHIVED:'ARCHIVED',
})
